# Numpy vs list

In [1]:
l=range(1000000)

In [2]:
import numpy as np
d=np.arange(1000000)

In [3]:
%time for i in range(1,10):res=[x*2 for x in l]

Wall time: 1.99 s


# ndarray

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.empty((4,6))

array([[ 3.81508044e-305,  9.70654404e-292,  3.30041299e-085,
         9.71042125e-292, -4.31113056e-167,  2.21719269e-301],
       [ 3.59515800e-306,  3.59585335e-306,  1.62610327e-260,
         4.10066150e-308,  4.39033156e-305,  5.98149210e-154],
       [ 3.98220466e+209,  9.92152728e+247,  6.01346953e-154,
         6.01347002e-154,  8.17735622e+141,  6.01347002e-154],
       [ 8.94213159e+130,  5.59506916e+141,  6.01347002e-154,
         1.17573841e+214,  4.85787506e-033,  4.48505083e-308]])

In [7]:
l=[2,3,4,5,6]
np.array(l)

array([2, 3, 4, 5, 6])

In [8]:
d=np.arange(10)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
d.shape

(10,)

In [10]:
x=np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
x.shape

(10, 10)

In [12]:
y=x.reshape(2,2,5,5)

In [13]:
x.ndim

2

In [14]:
x.dtype

dtype('float64')

# Arithmetic with ndarray

In [15]:
a=np.random.randn(10)

In [16]:
b=np.random.randn(10)

In [17]:
a

array([-0.75384778, -0.61112666, -2.38500326,  0.21605717, -2.12644784,
       -1.01923792, -0.60293678,  0.25936841, -1.28280084,  0.86645324])

In [18]:
b

array([-0.45117609,  0.49259259,  0.97300498,  0.78551116,  0.02037059,
        0.76754126, -0.20400578, -0.19116393,  0.51047383, -0.23094778])

In [19]:
a+b

array([-1.20502387, -0.11853407, -1.41199828,  1.00156833, -2.10607725,
       -0.25169667, -0.80694256,  0.06820449, -0.77232701,  0.63550546])

In [20]:
a-b

array([-0.30267169, -1.10371925, -3.35800824, -0.56945398, -2.14681844,
       -1.78677918, -0.39893099,  0.45053234, -1.79327467,  1.09740102])

In [21]:
a*b

array([ 0.3401181 , -0.30103647, -2.32062005,  0.16971532, -0.04331701,
       -0.78230716,  0.12300259, -0.04958188, -0.65483626, -0.20010545])

In [22]:
2*b

array([-0.90235219,  0.98518518,  1.94600996,  1.57102231,  0.04074119,
        1.53508251, -0.40801157, -0.38232785,  1.02094766, -0.46189556])

In [23]:
1/b

array([-2.2164295 ,  2.03007519,  1.02774397,  1.27305639, 49.09036785,
        1.30286156, -4.90182183, -5.23111245,  1.95896428, -4.32998317])

In [24]:
a>0

array([False, False, False,  True, False, False, False,  True, False,
        True])

In [25]:
a[a>1]

array([], dtype=float64)

# Indexing & Slicing

In [26]:
x=np.array([2,5,4,5,6,7,4])
x[0]

2

In [27]:
x[6]

4

In [28]:
len(x)

7

In [29]:
x[x>4]

array([5, 5, 6, 7])

In [30]:
x>4

array([False,  True, False,  True,  True,  True, False])

In [31]:
b=np.array([4,6,2,4,6,8])

In [32]:
b[[3,1]]

array([4, 6])

In [33]:
a=np.random.randn(4,10)

In [34]:
a[2:4,4:6]

array([[-0.6415779 ,  0.49582259],
       [ 1.01212232,  2.59739355]])

In [35]:
a[2][4]

-0.6415779012099695

In [36]:
d=np.ones((6,6))
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
d[1:-1,1:-1]=0
d

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [38]:
f=np.ones((10,10))

In [39]:
f[1:-1:3,1:-1:3]=0
f

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 0., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# Array Function

In [40]:
a=np.array([5,4,8,7,6,2,1,9])
np.sqrt(a)

array([2.23606798, 2.        , 2.82842712, 2.64575131, 2.44948974,
       1.41421356, 1.        , 3.        ])

In [41]:
np.power(a,4)

array([ 625,  256, 4096, 2401, 1296,   16,    1, 6561], dtype=int32)

# Numpy where Function

In [42]:
salary=np.array([-4,0,70000,50000,-2,45666])
np.where(salary <=0,25000,salary)

array([25000, 25000, 70000, 50000, 25000, 45666])

In [43]:
np.where (salary <=0,"not ok","ok")

array(['not ok', 'not ok', 'ok', 'ok', 'not ok', 'ok'], dtype='<U6')

In [44]:
np.where (salary==0,33333,salary)

array([   -4, 33333, 70000, 50000,    -2, 45666])

# Mathematical and statistical function

In [45]:
x=np.array([4,3,5,6,2,9])

In [46]:
x.mean()

4.833333333333333

In [47]:
x.cumsum()

array([ 4,  7, 12, 18, 20, 29], dtype=int32)

In [48]:
x.cumprod()

array([   4,   12,   60,  360,  720, 6480], dtype=int32)

In [49]:
y=x<5

In [50]:
y

array([ True,  True, False, False,  True, False])

In [51]:
y.sum()

3

In [52]:
y.any()

True

In [53]:
y.all()

False

In [54]:
x.sort()
x

array([2, 3, 4, 5, 6, 9])

In [55]:
c=np.array([4,4,3,8,6,8,8,9,2,3])

In [56]:
np.unique(c)

array([2, 3, 4, 6, 8, 9])

# File Input Output

In [57]:
x=[3,5,6,7,2,4]
y=[6,0,9,7,4,5]

In [58]:
x_array=np.save("xtest",x)

In [59]:
np.load("xtest.npy")

array([3, 5, 6, 7, 2, 4])

In [60]:
np.savez("xytest",x=x,y=y)

In [61]:
xy_arr=np.load("xytest.npz")

In [62]:
xy_arr

In [63]:
xy_arr['y']

array([6, 0, 9, 7, 4, 5])

# Linear algebra function

In [64]:
x=np.random.randn(3,2)

In [65]:
y=np.random.randn(2,3)

In [66]:
x

array([[ 0.59147839, -0.86334719],
       [-0.48649333,  1.34067912],
       [-0.96566825, -0.62244201]])

In [67]:
y

array([[ 1.78198744, -0.52098028, -0.63064209],
       [ 0.91255834,  0.3772951 ,  0.31132985]])

In [68]:
x.dot(y)

array([[ 0.26615238, -0.63388524, -0.64179692],
       [ 0.35652291,  0.7592851 ,  0.7241966 ],
       [-2.28882334,  0.2682498 ,  0.41520626]])

In [69]:
x.transpose()

array([[ 0.59147839, -0.48649333, -0.96566825],
       [-0.86334719,  1.34067912, -0.62244201]])

In [70]:
x.trace()

1.9321575118474956

# Pseudo Random Number

In [71]:
np.random.seed(4)

In [72]:
np.random.normal(size=(3,3))

array([[ 0.05056171,  0.49995133, -0.99590893],
       [ 0.69359851, -0.41830152, -1.58457724],
       [-0.64770677,  0.59857517,  0.33225003]])

In [73]:
np.random.uniform(size=(3,6))

array([[0.0089861 , 0.38657128, 0.04416006, 0.95665297, 0.43614665,
        0.94897731],
       [0.78630599, 0.8662893 , 0.17316542, 0.07494859, 0.60074272,
        0.16797218],
       [0.73338017, 0.40844386, 0.52790882, 0.93757158, 0.52169612,
        0.10819338]])

# Reshape

In [74]:
x=np.random.randn(4,5)
x

array([[-1.14747663,  0.15989294, -1.20894816,  2.22336022,  0.39429521],
       [ 1.69235772, -1.11281215,  1.63574754, -1.36096559, -0.65122583],
       [ 0.54245131,  0.04800625, -2.35807363, -1.10558404,  0.83783635],
       [ 2.08787087,  0.91484096, -0.27620335,  0.7965119 , -1.14379857]])

In [75]:
x.ndim

2

In [76]:
x.reshape(2,2,5)

array([[[-1.14747663,  0.15989294, -1.20894816,  2.22336022,
          0.39429521],
        [ 1.69235772, -1.11281215,  1.63574754, -1.36096559,
         -0.65122583]],

       [[ 0.54245131,  0.04800625, -2.35807363, -1.10558404,
          0.83783635],
        [ 2.08787087,  0.91484096, -0.27620335,  0.7965119 ,
         -1.14379857]]])

In [77]:
x.reshape((2,2,-1))

array([[[-1.14747663,  0.15989294, -1.20894816,  2.22336022,
          0.39429521],
        [ 1.69235772, -1.11281215,  1.63574754, -1.36096559,
         -0.65122583]],

       [[ 0.54245131,  0.04800625, -2.35807363, -1.10558404,
          0.83783635],
        [ 2.08787087,  0.91484096, -0.27620335,  0.7965119 ,
         -1.14379857]]])

In [78]:
x.reshape((2,2,5),order='F')

array([[[-1.14747663,  0.15989294, -1.20894816,  2.22336022,
          0.39429521],
        [ 0.54245131,  0.04800625, -2.35807363, -1.10558404,
          0.83783635]],

       [[ 1.69235772, -1.11281215,  1.63574754, -1.36096559,
         -0.65122583],
        [ 2.08787087,  0.91484096, -0.27620335,  0.7965119 ,
         -1.14379857]]])

In [79]:
x.reshape((2,2,-1))

array([[[-1.14747663,  0.15989294, -1.20894816,  2.22336022,
          0.39429521],
        [ 1.69235772, -1.11281215,  1.63574754, -1.36096559,
         -0.65122583]],

       [[ 0.54245131,  0.04800625, -2.35807363, -1.10558404,
          0.83783635],
        [ 2.08787087,  0.91484096, -0.27620335,  0.7965119 ,
         -1.14379857]]])

In [80]:
x.ravel()

array([-1.14747663,  0.15989294, -1.20894816,  2.22336022,  0.39429521,
        1.69235772, -1.11281215,  1.63574754, -1.36096559, -0.65122583,
        0.54245131,  0.04800625, -2.35807363, -1.10558404,  0.83783635,
        2.08787087,  0.91484096, -0.27620335,  0.7965119 , -1.14379857])

In [81]:
x.flatten()

array([-1.14747663,  0.15989294, -1.20894816,  2.22336022,  0.39429521,
        1.69235772, -1.11281215,  1.63574754, -1.36096559, -0.65122583,
        0.54245131,  0.04800625, -2.35807363, -1.10558404,  0.83783635,
        2.08787087,  0.91484096, -0.27620335,  0.7965119 , -1.14379857])

In [82]:
x.reshape(2,10)

array([[-1.14747663,  0.15989294, -1.20894816,  2.22336022,  0.39429521,
         1.69235772, -1.11281215,  1.63574754, -1.36096559, -0.65122583],
       [ 0.54245131,  0.04800625, -2.35807363, -1.10558404,  0.83783635,
         2.08787087,  0.91484096, -0.27620335,  0.7965119 , -1.14379857]])

# Concatenate

In [83]:
a=[[3,2,4,5],[7,5,9,6]]
arr1=np.array(a)

In [84]:
b=[[13,12,14,15],[17,15,19,16]]
arr2=np.array(b)

In [85]:
np.concatenate((arr1,arr2),axis=1)

array([[ 3,  2,  4,  5, 13, 12, 14, 15],
       [ 7,  5,  9,  6, 17, 15, 19, 16]])

In [86]:
np.concatenate((arr1,arr2),axis=0)

array([[ 3,  2,  4,  5],
       [ 7,  5,  9,  6],
       [13, 12, 14, 15],
       [17, 15, 19, 16]])

In [87]:
np.hstack((arr1,arr2))

array([[ 3,  2,  4,  5, 13, 12, 14, 15],
       [ 7,  5,  9,  6, 17, 15, 19, 16]])

In [88]:
np.vstack((arr1,arr2))

array([[ 3,  2,  4,  5],
       [ 7,  5,  9,  6],
       [13, 12, 14, 15],
       [17, 15, 19, 16]])

# Split

In [89]:
x=np.array([3,6,5,3,7,1,9,6])

In [90]:
np.split(x,[3,4])

[array([3, 6, 5]), array([3]), array([7, 1, 9, 6])]

In [91]:
y=[[3,7,6,4,53,23,45,43],[7,5,3,4,19,18,42,44]]

In [92]:
z=np.array(y)

In [93]:
np.split(z,[2,5],axis=1)

[array([[3, 7],
        [7, 5]]), array([[ 6,  4, 53],
        [ 3,  4, 19]]), array([[23, 45, 43],
        [18, 42, 44]])]

In [94]:
np.split(z,[1],axis=0)

[array([[ 3,  7,  6,  4, 53, 23, 45, 43]]),
 array([[ 7,  5,  3,  4, 19, 18, 42, 44]])]

# Repeat & Tile

In [96]:
x=np.array([4,5,6,7])
np.repeat(x,3)

array([4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7])

In [97]:
np.tile(x,2)

array([4, 5, 6, 7, 4, 5, 6, 7])