# Pandas Series

In [1]:
import pandas as pd

In [2]:
a=pd.Series([4,3,6,-8,6])
a

0    4
1    3
2    6
3   -8
4    6
dtype: int64

In [3]:
print(a.values)

[ 4  3  6 -8  6]


In [4]:
print(a.index)

RangeIndex(start=0, stop=5, step=1)


In [5]:
temp=pd.Series([34,25,65,43],index=['jan','dec','mar','jun'])
print(temp)
temp.index=['a','b','c','d']
temp

jan    34
dec    25
mar    65
jun    43
dtype: int64


a    34
b    25
c    65
d    43
dtype: int64

In [6]:
print(temp.index)

Index(['a', 'b', 'c', 'd'], dtype='object')


In [7]:
sandwich=pd.Series([34,44,35,66,45,71,56],index=["mon","tue","wed","thu","fri","sat","sun"])
sandwich

mon    34
tue    44
wed    35
thu    66
fri    45
sat    71
sun    56
dtype: int64

In [8]:
temp=pd.Series([34,25,65,43],index=['jan','dec','mar','jun'],name="4 month temp")
temp

jan    34
dec    25
mar    65
jun    43
Name: 4 month temp, dtype: int64

In [9]:
print(temp[1])

25


In [10]:
print(temp['mar'])

65


In [11]:
print(temp[[3,1]])

jun    43
dec    25
Name: 4 month temp, dtype: int64


In [12]:
print(temp[['mar','dec']])

mar    65
dec    25
Name: 4 month temp, dtype: int64


In [13]:
print(temp[temp>34])

mar    65
jun    43
Name: 4 month temp, dtype: int64


In [14]:
temp

jan    34
dec    25
mar    65
jun    43
Name: 4 month temp, dtype: int64

In [15]:
temp=temp*2
print(temp)

jan     68
dec     50
mar    130
jun     86
Name: 4 month temp, dtype: int64


In [16]:
temp=temp/2
print(temp)

jan    34.0
dec    25.0
mar    65.0
jun    43.0
Name: 4 month temp, dtype: float64


In [17]:
'mar' in temp

True

In [18]:
'jjj' in temp

False

In [19]:
import numpy as np
ar1=np.array([32,22,32,33,43,48])
ar2=np.array(['eng','maths','urdu','chemistry','physics','cs'])
obj=pd.Series(ar1,index=ar2)
obj

eng          32
maths        22
urdu         32
chemistry    33
physics      43
cs           48
dtype: int32

In [20]:
corono={'kp':500,'baluchistan':202,'sindh':900,'punjab':2080}
ps=pd.Series(corono)
print(ps)
print(ps.index)
print(ps.values)

kp              500
baluchistan     202
sindh           900
punjab         2080
dtype: int64
Index(['kp', 'baluchistan', 'sindh', 'punjab'], dtype='object')
[ 500  202  900 2080]


In [21]:
corono={'kp':500,'baluchistan':202,'sindh':900,'punjab':2080}
ps=pd.Series(corono,index=['punjab','baluchistan','sindh','kp','gb'])
print(ps)

punjab         2080.0
baluchistan     202.0
sindh           900.0
kp              500.0
gb                NaN
dtype: float64


In [22]:
print(ps)
print(pd.isnull(ps))
ps.isnull()

punjab         2080.0
baluchistan     202.0
sindh           900.0
kp              500.0
gb                NaN
dtype: float64
punjab         False
baluchistan    False
sindh          False
kp             False
gb              True
dtype: bool


punjab         False
baluchistan    False
sindh          False
kp             False
gb              True
dtype: bool

In [23]:
x=[23,24,43,44,19,92]
v=['a','b','c','d','e','f']
y=pd.Series(x,v)
print(y)


a    23
b    24
c    43
d    44
e    19
f    92
dtype: int64


In [24]:
ps.name="patients"
ps.index.name="provinces"
print(ps)
print(ps.index)

provinces
punjab         2080.0
baluchistan     202.0
sindh           900.0
kp              500.0
gb                NaN
Name: patients, dtype: float64
Index(['punjab', 'baluchistan', 'sindh', 'kp', 'gb'], dtype='object', name='provinces')


# Pandas DataFrame

In [25]:
patients=pd.Series([500,2076,209,902])
dieds=pd.Series([17,15,4,9])
print(patients,dieds)
data={"patients":patients,"dieds":dieds}
df=pd.DataFrame(data)
print(df)

0     500
1    2076
2     209
3     902
dtype: int64 0    17
1    15
2     4
3     9
dtype: int64
   patients  dieds
0       500     17
1      2076     15
2       209      4
3       902      9


In [26]:
state=['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada']
data={"state":state,
     "Year":[2000,2001,2002,2001,2002,2003],
     "pop":[1.5,1.7,3.6,2.4,2.9,3.2]}
frame=pd.DataFrame(data,index=['1st','2nd','3rd','4th','5th','6ht',])
print(frame)

      state  Year  pop
1st    Ohio  2000  1.5
2nd    Ohio  2001  1.7
3rd    Ohio  2002  3.6
4th  Nevada  2001  2.4
5th  Nevada  2002  2.9
6ht  Nevada  2003  3.2


In [27]:
state_df=pd.DataFrame(data,columns=['pop','state','year'])
state_df.head()

pop   state year
0  1.5    Ohio  NaN
1  1.7    Ohio  NaN
2  3.6    Ohio  NaN
3  2.4  Nevada  NaN
4  2.9  Nevada  NaN

In [28]:
state_df=pd.DataFrame(data,columns=['pop','state','Year','debt'],index=['1st','2nd','3rd','4th','5th','6th'])
state_df

pop   state  Year debt
1st  1.5    Ohio  2000  NaN
2nd  1.7    Ohio  2001  NaN
3rd  3.6    Ohio  2002  NaN
4th  2.4  Nevada  2001  NaN
5th  2.9  Nevada  2002  NaN
6th  3.2  Nevada  2003  NaN

In [29]:
state_df.head()

pop   state  Year debt
1st  1.5    Ohio  2000  NaN
2nd  1.7    Ohio  2001  NaN
3rd  3.6    Ohio  2002  NaN
4th  2.4  Nevada  2001  NaN
5th  2.9  Nevada  2002  NaN

In [30]:
print(state_df.columns)
print(state_df.index)

Index(['pop', 'state', 'Year', 'debt'], dtype='object')
Index(['1st', '2nd', '3rd', '4th', '5th', '6th'], dtype='object')


In [31]:
#print(data)
#print(data['state'])
#print(data['pop'])
print(state_df['state'])

1st      Ohio
2nd      Ohio
3rd      Ohio
4th    Nevada
5th    Nevada
6th    Nevada
Name: state, dtype: object


In [32]:
state_df.state

1st      Ohio
2nd      Ohio
3rd      Ohio
4th    Nevada
5th    Nevada
6th    Nevada
Name: state, dtype: object

In [33]:
state_df.loc['4th']

pop         2.4
state    Nevada
Year       2001
debt        NaN
Name: 4th, dtype: object

In [34]:
ln=len(state_df)
rng=np.arange(ln)
print(rng)
state_df['debt']=rng
#state_df['debt']=16
print(state_df)

[0 1 2 3 4 5]
     pop   state  Year  debt
1st  1.5    Ohio  2000     0
2nd  1.7    Ohio  2001     1
3rd  3.6    Ohio  2002     2
4th  2.4  Nevada  2001     3
5th  2.9  Nevada  2002     4
6th  3.2  Nevada  2003     5


In [35]:
d=pd.Series(['12','14','19','32','31','21'],index=['1st','3rd','5th','4th','2nd','6th'])
state_df['debt']=d
state_df

pop   state  Year debt
1st  1.5    Ohio  2000   12
2nd  1.7    Ohio  2001   31
3rd  3.6    Ohio  2002   14
4th  2.4  Nevada  2001   32
5th  2.9  Nevada  2002   19
6th  3.2  Nevada  2003   21